kind: ConfigMap 
apiVersion: v1 
metadata:
  name: mycm
data:
    MONGO_INITDB_ROOT_USERNAME: admin
    MONGO_INITDB_ROOT_PASSWORD: password
    DB_URL: mongodb://admin:password@10.191.235.225:31003
      
