--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  creationTimestamp: null
  labels: 
    app: home
  name: home
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: home
  strategy: {}
  template: 
    metadata: 
      creationTimestamp: null
      labels: 
        app: home
    spec:
      volumes:
       - name: pv-storage
         persistentVolumeClaim:
          claimName: mypvc
      containers: 
        - image: "samiksha18/home-hera:latest"
          name: homec
          volumeMounts:
           - mountPath: "/mnt"
             name: pv-storage
          envFrom:
          - configMapRef:
              name: mycm
          ports: 
          - containerPort: 3003
          resources: {}
status: {}

