apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: jobs
  name: jobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: jobs
    spec:
      volumes:
       - name: pv-storage
         persistentVolumeClaim:
          claimName: mypvc
      containers:
      - image: "samiksha18/jobs-hera:latest"
        name: jobsc
        volumeMounts:
         - mountPath: "/var/lib/data"
           name: pv-storage
        envFrom:
          - configMapRef:
              name: mycm
        ports:
        - containerPort: 3001
        resources: {}
status: {}


