apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: login
    spec:
      volumes:
       - name: pv-storage
         persistentVolumeClaim:
          claimName: mypvc
      containers:
      - image: "samiksha18/login-hera:latest"
        name: loginc
        volumeMounts:
         - mountPath: "/var/lib/data"
           name: pv-storage
        envFrom:
          - configMapRef:
              name: mycm
        ports:
        - containerPort: 3000
        resources: {}
status: {}


