apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: login
  name: login
spec:
  replicas: 1
  selector:
    matchLabels:
      app: login
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: login
    spec:
      containers:
      - image: samiksha18/login-hera:latest
        name: loginc
        env:
        - name: DB_URL
          value: "mongodb://10.191.235.225:31003"
        ports:
        - containerPort: 3000
        resources: {}
status: {}


