apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongo
    spec:
      volumes:
       - name: pv-storage
         persistentVolumeClaim:
            claimName: mypvc
      containers:
      - image: mongo
        name: mongo
        volumeMounts:
         - name: pv-storage
           mountPath: /mnt
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        - name: DB_URL
          value: "mongodb://admin:password@10.191.235.225:31003"
        resources: {}
status: {}
