apiVersion: v1
kind: Service
metadata:
  name: mongonp
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  type: LoadBalancer
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 31003
