apiVersion: v1
kind: Service
metadata:
  name: jobsnp
  labels:
    app: ci-cd-jobs
spec:
  selector:
    app: jobs
  type: LoadBalancer
  ports:
    - port: 3001
      targetPort: 3001
      nodePort: 31002
