apiVersion: v1
kind: Service
metadata:
  name: homenp
  labels:
    app: ci-cd-home
spec:
  selector:
    app: home
  type: LoadBalancer
  ports:
    - port: 3003
      targetPort: 3003
      nodePort: 31000
