apiVersion: v1
kind: Service
metadata:
  name: loginnp
  labels:
    app: ci-cd-login
spec:
  selector:
    app: login
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 31001
