apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mypvc
spec:
        storageClassName: pv-storage
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 2G
