---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv1
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-storage
  nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - kube02-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mypvc1
spec:
        storageClassName: pv-storage
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 2G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv2
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv2
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-storage
  nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - kube02-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mypvc2
spec:
        storageClassName: pv-storage
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 2G
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv3
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/pv3
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: pv-storage
  nodeAffinity:
   required:
     nodeSelectorTerms:
     - matchExpressions:
       - key: kubernetes.io/hostname
         operator: In
         values:
         - kube02-node
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
        name: mypvc3
spec:
        storageClassName: pv-storage
        accessModes:
                - ReadWriteMany
        resources:
                requests:
                        storage: 2G

