apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels: 
    app: mongo
spec:
  selector:
    matchLabels:
      role: mongo
      app: mongo
      environment: test
  serviceName: "mongo"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongo
        app: mongo
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mypvcss
            mountPath: /data/db
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "admin"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "password"
        - name: DB_URL
          value: "mongodb://admin:password@10.191.235.225:31003"
  volumeClaimTemplates:
    - metadata:
        name: mypvcss
      spec:
        storageClassName: pv-storage
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 2G  
