---
- hosts: kubernetes
  tasks:
  - name: run all deployment yamls
    shell: |
     kubectl delete svc homecl homenp jobscl jobsnp logincl loginnp mongocl mongonp;
     kubectl delete deploy home jobs login mongo;
     cd /home/ubuntu/hera_new;
     kubectl apply -f devops/;

  - name: print message
    debug:
      msg: "files have been deployed"


